FROM python:3.7-slim-buster

# expose port
EXPOSE 8000

# install chromedriver
RUN apt-get update && apt-get install -y \
    chromium-driver

# upgrade pip
RUN pip install --upgrade pip

# install selenium
RUN pip install selenium

# add the script to where selenium is installed
ADD main.py /usr/local/lib/python3.7/site-packages

RUN groupadd -r appuser && useradd -r -g appuser appuser
USER appuser

# run the script
CMD [ "python3.7", "/usr/local/lib/python3.7/site-packages/main.py"]
